const PRODUCT={"slug":"zk-proof-packer","name":"ZK Proof Packer","kind":"crypto","description":"Size ZK proof bytes, public inputs, and instructions before building a v1 transaction."};
const source=document.querySelector('#source'),output=document.querySelector('#output'),bytesEl=document.querySelector('#bytes'),partsEl=document.querySelector('#parts'),savedEl=document.querySelector('#saved'),meter=document.querySelector('#meter'),notice=document.querySelector('#notice');
const example="proofBytes=2048\npublicInputsBytes=320\nsignatures=4\naccounts=12\ninstructionBytes=180";source.value=example;
const encoder=new TextEncoder();const hex=value=>Array.from(encoder.encode(value),byte=>byte.toString(16).padStart(2,'0')).join('');
async function digest(value){const hash=await crypto.subtle.digest('SHA-256',encoder.encode(value));return Array.from(new Uint8Array(hash),b=>b.toString(16).padStart(2,'0')).join('');}
function fields(value){return Object.fromEntries(value.split(/\n+/).map(line=>line.split(/[:=]/,2).map(x=>x.trim())).filter(pair=>pair.length===2));}
async function artifact(value){const hash=await digest(value);const base={protocol:'txv1-labs/1',product:PRODUCT.slug,type:PRODUCT.kind,createdAt:new Date().toISOString(),contentHash:'sha256:'+hash};
if(PRODUCT.kind==='art')return {...base,render:'svg-or-data-uri',content:value};
if(PRODUCT.kind==='agent')return {...base,agent:fields(value),owner:'wallet-signature-required'};
if(PRODUCT.kind==='token')return {...base,token2022:fields(value),atomicPlan:['createMint','createATA','mintTo','setAuthority']};
if(PRODUCT.kind==='proof')return {...base,claim:value,verification:['contentHash','ownerSignature','blockTime']};
if(PRODUCT.kind==='batch')return {...base,divisible:false,instructions:value.split(/\n+/).filter(Boolean)};
if(PRODUCT.kind==='crypto')return {...base,schemeStudy:fields(value),warning:'Sizing model; no proof verification is performed.'};
if(PRODUCT.kind==='security')return {...base,disclosures:fields(value),score:'review-required'};
if(PRODUCT.kind==='trend')return {...base,query:fields(value),rpc:{maxSupportedTransactionVersion:1}};
if(PRODUCT.kind==='evm')return {...base,evm:fields(value),calldata:'0x'+hex(value),solanaEnvelope:'first/1'};
return {...base,transactionConfig:{computeUnitLimit:'simulate',loadedAccountsDataSizeLimit:'simulate',priorityFeeLamports:5000},inputs:fields(value),source:value};}
async function generate(){const result=await artifact(source.value.trim());const text=JSON.stringify(result,null,2);output.textContent=text;const size=encoder.encode(text).byteLength;const v1=Math.max(1,Math.ceil((size+320)/4096));const legacy=Math.max(1,Math.ceil((size+220)/1232));bytesEl.textContent=size.toLocaleString();partsEl.textContent=String(v1);savedEl.textContent=String(Math.max(0,legacy-v1));meter.style.width=Math.min(100,(size+320)/4096*100)+'%';meter.classList.toggle('over',size+320>4096);notice.textContent=size+320<=4096?'Estimated to fit one v1 transaction with conservative overhead.':'Requires multipart envelopes; content remains UTF-8 safe.';return text;}
document.querySelector('#generate').onclick=generate;document.querySelector('#example').onclick=()=>{source.value=example;generate()};document.querySelector('#copy').onclick=async()=>navigator.clipboard.writeText(output.textContent);document.querySelector('#download').onclick=()=>{const blob=new Blob([output.textContent],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=PRODUCT.slug+'-payload.json';a.click();URL.revokeObjectURL(a.href)};
const registered=new Set();const api={register(...wallets){wallets.forEach(wallet=>registered.add(wallet));return()=>wallets.forEach(wallet=>registered.delete(wallet))}};try{window.addEventListener('wallet-standard:register-wallet',event=>event.detail(api));window.dispatchEvent(new CustomEvent('wallet-standard:app-ready',{detail:api}))}catch{}
document.querySelector('#wallet').onclick=async event=>{try{if(PRODUCT.kind==='evm'&&window.ethereum){const [account]=await window.ethereum.request({method:'eth_requestAccounts'});event.currentTarget.textContent=account.slice(0,6)+'…'+account.slice(-4);return}const wallet=[...registered].find(item=>item.features?.['standard:connect']);if(!wallet)throw new Error('No Wallet Standard wallet detected');const result=await wallet.features['standard:connect'].connect();const account=result.accounts?.[0]||wallet.accounts?.[0];if(!account)throw new Error('Wallet returned no account');const send=wallet.features?.['solana:signAndSendTransaction'];const versions=send?.supportedTransactionVersions;const v1=versions?.includes?.(1)||versions?.has?.(1);event.currentTarget.textContent=account.address.slice(0,4)+'…'+account.address.slice(-4)+(v1?' · v1':' · no v1');}catch(error){notice.textContent=error.message}};generate();
